name: NutriCam
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0

  firebase_auth: 4.19.4
  firebase_core: ^2.32.0
  cloud_firestore: ^4.16.1
  fluttertoast: ^8.2.5
  image_picker: ^1.1.0
  firebase_storage: ^11.6.0
  http: ^1.5.0
  imagekit_io: ^0.0.3
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/back/
    - assets/iconos/
    - assets/logo/
    - assets/iconos/button_navigator/
    - assets/iconos/comidas/
