// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsi8j8zLRMypkYYfyqSh3jBWjKKtsgLi0',
    appId: '1:199740199301:web:cb9e73bf7442b28a5774ec',
    messagingSenderId: '199740199301',
    projectId: 'nutriscan-4cd29',
    authDomain: 'nutriscan-4cd29.firebaseapp.com',
    storageBucket: 'nutriscan-4cd29.firebasestorage.app',
    measurementId: 'G-ZTJYCN9CYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIftxf6OIBp-McBB7KIlSgddokC6dvf0o',
    appId: '1:199740199301:android:9e05570da1746f8a5774ec',
    messagingSenderId: '199740199301',
    projectId: 'nutriscan-4cd29',
    storageBucket: 'nutriscan-4cd29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcTwxHvEz25Yzen_FDk9cQWRxAwtSVpE',
    appId: '1:199740199301:ios:722ecea3af86cc355774ec',
    messagingSenderId: '199740199301',
    projectId: 'nutriscan-4cd29',
    storageBucket: 'nutriscan-4cd29.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlcTwxHvEz25Yzen_FDk9cQWRxAwtSVpE',
    appId: '1:199740199301:ios:ed06885d529047165774ec',
    messagingSenderId: '199740199301',
    projectId: 'nutriscan-4cd29',
    storageBucket: 'nutriscan-4cd29.firebasestorage.app',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
